title: TTP Report
email: contact@ttp.report
author:
  twitter: ttpreport
twitter:
  username: ttpreport
  card: summary

social:
  name: TTP Report
  links:
    - https://twitter.com/ttpreport
    - https://github.com/ttpreport

description: >-
  No-nonsense breakdown of adversary tactics, techniques and procedures 
baseurl: ""
url: "https://ttp.report"
twitter_link: "https://twitter.com/ttpreport"
github_link:  "https://github.com/ttpreport"
telegram_link: "https://t.me/ttpreport"
copyright: TTP Report (cleft) {currentYear}
google_analytics: G-G048T8EH4N

logo: "/assets/images/banners/ttp-ava-round.png"
favicon:
  32x32: "/assets/images/banners/favicon-32x32.png"
  16x16: "/assets/images/banners/favicon-16x16.png"
  apple-touch: "/assets/images/banners/apple-touch-icon.png"
  safari-tab: "/assets/images/banners/safari-pinned-tab.svg"
  webmanifest: "/assets/images/banners/site.webmanifest"

# Build settings
remote_theme: "jeffreytse/jekyll-theme-yat"
night_mode: "on"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
